## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow import keras

#Connect to Google Drive to access data resource and export files
from google.colab import drive, files
drive.mount('/content/drive')

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("/content/drive/MyDrive/CoLabs/deep-learning-challenge/Resources/charity_data.csv")
application_df.head()

#Target: IS_SUCCESSFUL
#Features: APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, INCOME_AMT, SPECIAL_CONSIDERATIONS, ASK_AMT

Mounted at /content/drive

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN', 'NAME', 'STATUS'], inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#cutoff value = 100
application_types_to_replace = []
for value in application_df['APPLICATION_TYPE']: 
  if value in application_types_to_replace:
    continue
  elif application_df['APPLICATION_TYPE'].value_counts()[value] < 100:
    application_types_to_replace.append(value)

#print(f"Application types to replace: {application_types_to_replace}")

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#create a variables out of the value counts
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
#filter that variable for values with counts >1 and store as new variable
classification_value_counts_gt1 = classification_value_counts[classification_value_counts>1]
#print new variable
classification_value_counts_gt1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#cutoff value = 100
classifications_to_replace = []
for value in application_df['CLASSIFICATION']: 
  if value in classifications_to_replace:
    continue
  elif application_df['CLASSIFICATION'].value_counts()[value] < 100:
    classifications_to_replace.append(value)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`

# non-numeric columns: APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, INCOME_AMT, SPECIAL_CONSIDERATIONS, ASK_AMT
#create a dataframe with dummy data
optimize_1_df = pd.get_dummies(data=application_df, columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])
optimize_1_df

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,5000,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,108590,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,5000,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,6692,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,142590,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,5000,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,5000,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,5000,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,36500179,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = optimize_1_df['IS_SUCCESSFUL'].values
X = optimize_1_df.drop(['IS_SUCCESSFUL'],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

<ipython-input-10-11760197e840>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = optimize_1_df.drop(['IS_SUCCESSFUL'],1).values

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)



```
# This is formatted as code
```
#Optimization 1
## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  50
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

#Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                2500

 dense_1 (Dense)             (None, 30)                1530

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 4,351
Trainable params: 4,351
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
my_callbacks = keras.callbacks.ModelCheckpoint(filepath='/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/saved_model_weights_optimizer1.h5', save_weights_only=True, save_freq=5)

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[my_callbacks])

Epoch 1/100
804/804 [==============================] - 10s 10ms/step - loss: 0.5743 - accuracy: 0.7151
Epoch 2/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5517 - accuracy: 0.7288
Epoch 3/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5488 - accuracy: 0.7314
Epoch 4/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5478 - accuracy: 0.7315
Epoch 5/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5464 - accuracy: 0.7310
Epoch 6/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5459 - accuracy: 0.7327
Epoch 7/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5453 - accuracy: 0.7338
Epoch 8/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5450 - accuracy: 0.7336
Epoch 9/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5434 - accuracy: 0.7339
Epoch 10/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5436 - accuracy: 0.7340
Epoch 11/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5431 - accuracy: 0.7338
Epoch 12/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5428 - accuracy: 0.7343
Epoch 13/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5420 - accuracy: 0.7345
Epoch 14/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5414 - accuracy: 0.7347
Epoch 15/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5408 - accuracy: 0.7348
Epoch 16/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5408 - accuracy: 0.7353
Epoch 17/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5399 - accuracy: 0.7353
Epoch 18/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5406 - accuracy: 0.7362
Epoch 19/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5397 - accuracy: 0.7357
Epoch 20/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5397 - accuracy: 0.7364
Epoch 21/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5391 - accuracy: 0.7365
Epoch 22/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5389 - accuracy: 0.7374
Epoch 23/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5386 - accuracy: 0.7363
Epoch 24/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5388 - accuracy: 0.7364
Epoch 25/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5380 - accuracy: 0.7364
Epoch 26/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5381 - accuracy: 0.7364
Epoch 27/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5374 - accuracy: 0.7374
Epoch 28/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5373 - accuracy: 0.7379
Epoch 29/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5373 - accuracy: 0.7382
Epoch 30/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5369 - accuracy: 0.7375
Epoch 31/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5370 - accuracy: 0.7374
Epoch 32/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5367 - accuracy: 0.7376
Epoch 33/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5367 - accuracy: 0.7378
Epoch 34/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5362 - accuracy: 0.7374
Epoch 35/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5362 - accuracy: 0.7389
Epoch 36/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5360 - accuracy: 0.7378
Epoch 37/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5360 - accuracy: 0.7384
Epoch 38/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5356 - accuracy: 0.7393
Epoch 39/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5357 - accuracy: 0.7378
Epoch 40/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 41/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5352 - accuracy: 0.7387
Epoch 42/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5353 - accuracy: 0.7386
Epoch 43/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5345 - accuracy: 0.7392
Epoch 44/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5349 - accuracy: 0.7384
Epoch 45/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5345 - accuracy: 0.7388
Epoch 46/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5350 - accuracy: 0.7387
Epoch 47/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5340 - accuracy: 0.7393
Epoch 48/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5341 - accuracy: 0.7388
Epoch 49/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5345 - accuracy: 0.7388
Epoch 50/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5342 - accuracy: 0.7387
Epoch 51/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5339 - accuracy: 0.7398
Epoch 52/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5341 - accuracy: 0.7394
Epoch 53/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5338 - accuracy: 0.7407
Epoch 54/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5337 - accuracy: 0.7399
Epoch 55/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5336 - accuracy: 0.7396
Epoch 56/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5337 - accuracy: 0.7397
Epoch 57/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5335 - accuracy: 0.7388
Epoch 58/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5341 - accuracy: 0.7403
Epoch 59/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5333 - accuracy: 0.7393
Epoch 60/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5331 - accuracy: 0.7383
Epoch 61/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 62/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5333 - accuracy: 0.7396
Epoch 63/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5327 - accuracy: 0.7397
Epoch 64/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5328 - accuracy: 0.7399
Epoch 65/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5331 - accuracy: 0.7398
Epoch 66/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5329 - accuracy: 0.7406
Epoch 67/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5329 - accuracy: 0.7403
Epoch 68/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5326 - accuracy: 0.7393
Epoch 69/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5326 - accuracy: 0.7399
Epoch 70/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5324 - accuracy: 0.7400
Epoch 71/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5324 - accuracy: 0.7399
Epoch 72/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 73/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5324 - accuracy: 0.7403
Epoch 74/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5321 - accuracy: 0.7399
Epoch 75/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5321 - accuracy: 0.7403
Epoch 76/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5324 - accuracy: 0.7399
Epoch 77/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5322 - accuracy: 0.7395
Epoch 78/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5317 - accuracy: 0.7408
Epoch 79/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5320 - accuracy: 0.7400
Epoch 80/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5316 - accuracy: 0.7404
Epoch 81/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5317 - accuracy: 0.7401
Epoch 82/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5317 - accuracy: 0.7399
Epoch 83/100
804/804 [==============================] - 9s 12ms/step - loss: 0.5319 - accuracy: 0.7405
Epoch 84/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5317 - accuracy: 0.7409
Epoch 85/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5319 - accuracy: 0.7398
Epoch 86/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 87/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5313 - accuracy: 0.7403
Epoch 88/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5312 - accuracy: 0.7407
Epoch 89/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5315 - accuracy: 0.7402
Epoch 90/100
804/804 [==============================] - 10s 12ms/step - loss: 0.5315 - accuracy: 0.7396
Epoch 91/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5320 - accuracy: 0.7398
Epoch 92/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5310 - accuracy: 0.7397
Epoch 93/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5313 - accuracy: 0.7406
Epoch 94/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5309 - accuracy: 0.7408
Epoch 95/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5309 - accuracy: 0.7410
Epoch 96/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5312 - accuracy: 0.7406
Epoch 97/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5309 - accuracy: 0.7406
Epoch 98/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5314 - accuracy: 0.7410
Epoch 99/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5311 - accuracy: 0.7410
Epoch 100/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5309 - accuracy: 0.7405

In [15]:
# Evaluate the model using the test data
model_loss_1, model_accuracy_1 = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"\nOptimizer 1 \n Loss: {model_loss_1}, Accuracy: {model_accuracy_1}")

268/268 - 2s - loss: 0.5614 - accuracy: 0.7326 - 2s/epoch - 6ms/step

Optimizer 1
 Loss: 0.5614355802536011, Accuracy: 0.7325947284698486

In [16]:
# Export our model to HDF5 file
nn.save('/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/AlphabetSoupCharity_Optimized_1.h5')

#Create Optimization #2
Model optimizations: 
1. Changed data preprocessing: 
  * Added more CLASSIFICATION and APPLICATION_TYPE features. 
  * Removed ASK_AMT and SPECIAL_CONSIDERATIONS
2. Used sigmoid as the activation for each layer
3. Changed optimizer to sgd

In [17]:
application_df_2 = pd.read_csv("/content/drive/MyDrive/CoLabs/deep-learning-challenge/Resources/charity_data.csv")
application_df_2.drop(columns=['EIN', 'NAME', 'STATUS'], inplace=True)
application_df_2.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,N,142590,1

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#cutoff value = 10
application_types_to_replace = []
for value in application_df_2['APPLICATION_TYPE']: 
  if value in application_types_to_replace:
    continue
  elif application_df_2['APPLICATION_TYPE'].value_counts()[value] < 10:
    application_types_to_replace.append(value)

#print(f"Application types to replace: {application_types_to_replace}")

# Replace in dataframe
for app in application_types_to_replace:
    application_df_2['APPLICATION_TYPE'] = application_df_2['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df_2['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [19]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#cutoff value = 10
classifications_to_replace = []
for value in application_df_2['CLASSIFICATION']: 
  if value in classifications_to_replace:
    continue
  elif application_df_2['CLASSIFICATION'].value_counts()[value] < 10:
    classifications_to_replace.append(value)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df_2['CLASSIFICATION'] = application_df_2['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df_2['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: CLASSIFICATION, dtype: int64

In [20]:
#drop additional columns
application_df_2.drop(columns=['ASK_AMT', 'SPECIAL_CONSIDERATIONS'], inplace=True)

# Convert categorical data to numeric with `pd.get_dummies`
# non-numeric columns: APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, INCOME_AMT, SPECIAL_CONSIDERATIONS, ASK_AMT
#create a dataframe with dummy data
optimize_2_df = pd.get_dummies(data=application_df_2, columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT'])
optimize_2_df

,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,1,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34295,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34296,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
34297,1,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
34298,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0

In [21]:
# Split our preprocessed data into our features and target arrays
y = optimize_2_df['IS_SUCCESSFUL'].values
X = optimize_2_df.drop(['IS_SUCCESSFUL'],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

<ipython-input-21-2f0a66de43e6>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = optimize_2_df.drop(['IS_SUCCESSFUL'],1).values

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  68
hidden_nodes_layer2 = 40
hidden_nodes_layer3 = 10
nn_2 = tf.keras.models.Sequential()

# First hidden layer
nn_2.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="sigmoid")
)
# Second hidden layer
nn_2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

#Third hidden layer
nn_2.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn_2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 68)                4624

 dense_5 (Dense)             (None, 40)                2760

 dense_6 (Dense)             (None, 10)                410

 dense_7 (Dense)             (None, 1)                 11

=================================================================
Total params: 7,805
Trainable params: 7,805
Non-trainable params: 0
_________________________________________________________________

In [23]:
# Compile the model
nn_2.compile(loss="binary_crossentropy", optimizer="sgd", metrics=["accuracy"])

In [24]:
my_callbacks = keras.callbacks.ModelCheckpoint(filepath='/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/saved_model_weights_optimizer2.h5', save_weights_only=True, save_freq=5)

# Train the model
fit_model = nn_2.fit(X_train_scaled, y_train, epochs=100, callbacks=[my_callbacks])

Epoch 1/100
804/804 [==============================] - 8s 9ms/step - loss: 0.6933 - accuracy: 0.5205
Epoch 2/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6902 - accuracy: 0.5317
Epoch 3/100
804/804 [==============================] - 7s 8ms/step - loss: 0.6890 - accuracy: 0.5318
Epoch 4/100
804/804 [==============================] - 7s 8ms/step - loss: 0.6877 - accuracy: 0.5317
Epoch 5/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6861 - accuracy: 0.5317
Epoch 6/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6843 - accuracy: 0.5317
Epoch 7/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6818 - accuracy: 0.5356
Epoch 8/100
804/804 [==============================] - 7s 8ms/step - loss: 0.6788 - accuracy: 0.5461
Epoch 9/100
804/804 [==============================] - 6s 7ms/step - loss: 0.6746 - accuracy: 0.5805
Epoch 10/100
804/804 [==============================] - 7s 9ms/step - loss: 0.6689 - accuracy: 0.6266
Epoch 11/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6613 - accuracy: 0.6560
Epoch 12/100
804/804 [==============================] - 7s 9ms/step - loss: 0.6511 - accuracy: 0.6759
Epoch 13/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6385 - accuracy: 0.6946
Epoch 14/100
804/804 [==============================] - 7s 8ms/step - loss: 0.6248 - accuracy: 0.7018
Epoch 15/100
804/804 [==============================] - 6s 8ms/step - loss: 0.6121 - accuracy: 0.7027
Epoch 16/100
804/804 [==============================] - 7s 9ms/step - loss: 0.6016 - accuracy: 0.7042
Epoch 17/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5938 - accuracy: 0.7077
Epoch 18/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5880 - accuracy: 0.7170
Epoch 19/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5837 - accuracy: 0.7208
Epoch 20/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5807 - accuracy: 0.7220
Epoch 21/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5785 - accuracy: 0.7235
Epoch 22/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5767 - accuracy: 0.7235
Epoch 23/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5753 - accuracy: 0.7235
Epoch 24/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5743 - accuracy: 0.7240
Epoch 25/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5735 - accuracy: 0.7245
Epoch 26/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5728 - accuracy: 0.7248
Epoch 27/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5722 - accuracy: 0.7251
Epoch 28/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5717 - accuracy: 0.7248
Epoch 29/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5713 - accuracy: 0.7248
Epoch 30/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5708 - accuracy: 0.7247
Epoch 31/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5706 - accuracy: 0.7249
Epoch 32/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5702 - accuracy: 0.7251
Epoch 33/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5699 - accuracy: 0.7257
Epoch 34/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5696 - accuracy: 0.7248
Epoch 35/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5693 - accuracy: 0.7250
Epoch 36/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5690 - accuracy: 0.7260
Epoch 37/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5688 - accuracy: 0.7251
Epoch 38/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5687 - accuracy: 0.7259
Epoch 39/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5684 - accuracy: 0.7260
Epoch 40/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5682 - accuracy: 0.7257
Epoch 41/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5680 - accuracy: 0.7262
Epoch 42/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5678 - accuracy: 0.7257
Epoch 43/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5676 - accuracy: 0.7258
Epoch 44/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5675 - accuracy: 0.7260
Epoch 45/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5674 - accuracy: 0.7259
Epoch 46/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5672 - accuracy: 0.7268
Epoch 47/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5670 - accuracy: 0.7264
Epoch 48/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5668 - accuracy: 0.7262
Epoch 49/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5666 - accuracy: 0.7267
Epoch 50/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5664 - accuracy: 0.7265
Epoch 51/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5663 - accuracy: 0.7267
Epoch 52/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5661 - accuracy: 0.7264
Epoch 53/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5661 - accuracy: 0.7267
Epoch 54/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5659 - accuracy: 0.7269
Epoch 55/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5656 - accuracy: 0.7266
Epoch 56/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5655 - accuracy: 0.7269
Epoch 57/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5653 - accuracy: 0.7270
Epoch 58/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5653 - accuracy: 0.7269
Epoch 59/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5650 - accuracy: 0.7269
Epoch 60/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5649 - accuracy: 0.7272
Epoch 61/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5648 - accuracy: 0.7269
Epoch 62/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5646 - accuracy: 0.7271
Epoch 63/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5644 - accuracy: 0.7268
Epoch 64/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5643 - accuracy: 0.7269
Epoch 65/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5641 - accuracy: 0.7270
Epoch 66/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5641 - accuracy: 0.7272
Epoch 67/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5640 - accuracy: 0.7271
Epoch 68/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5638 - accuracy: 0.7269
Epoch 69/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5637 - accuracy: 0.7273
Epoch 70/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5635 - accuracy: 0.7272
Epoch 71/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5632 - accuracy: 0.7271
Epoch 72/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5631 - accuracy: 0.7272
Epoch 73/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5631 - accuracy: 0.7273
Epoch 74/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5628 - accuracy: 0.7273
Epoch 75/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5628 - accuracy: 0.7273
Epoch 76/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5626 - accuracy: 0.7275
Epoch 77/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5625 - accuracy: 0.7275
Epoch 78/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5623 - accuracy: 0.7272
Epoch 79/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5621 - accuracy: 0.7275
Epoch 80/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5619 - accuracy: 0.7278
Epoch 81/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5617 - accuracy: 0.7274
Epoch 82/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5616 - accuracy: 0.7276
Epoch 83/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5615 - accuracy: 0.7277
Epoch 84/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5613 - accuracy: 0.7276
Epoch 85/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5612 - accuracy: 0.7273
Epoch 86/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5609 - accuracy: 0.7277
Epoch 87/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5608 - accuracy: 0.7278
Epoch 88/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5607 - accuracy: 0.7278
Epoch 89/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5606 - accuracy: 0.7276
Epoch 90/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5604 - accuracy: 0.7275
Epoch 91/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5601 - accuracy: 0.7278
Epoch 92/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5599 - accuracy: 0.7280
Epoch 93/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5598 - accuracy: 0.7280
Epoch 94/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5597 - accuracy: 0.7278
Epoch 95/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5595 - accuracy: 0.7277
Epoch 96/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5593 - accuracy: 0.7280
Epoch 97/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5592 - accuracy: 0.7279
Epoch 98/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5590 - accuracy: 0.7283
Epoch 99/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5588 - accuracy: 0.7283
Epoch 100/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5586 - accuracy: 0.7286

In [25]:
# Evaluate the model using the test data
model_loss_2, model_accuracy_2 = nn_2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"\nOptimizer 2 \n Loss: {model_loss_2}, Accuracy: {model_accuracy_2}")

268/268 - 1s - loss: 0.5636 - accuracy: 0.7284 - 566ms/epoch - 2ms/step

Optimizer 2
 Loss: 0.563554584980011, Accuracy: 0.728396475315094

In [26]:
# Export our model to HDF5 file
nn_2.save('/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/AlphabetSoupCharity_Optimized_2.h5')

# Optimizer 3
Model optimizations: 
1. Changed data preprocessing: 
  * Dropped CLASSIFICATION, SPECIAL_CONSIDERATIONS, ASK_AMT 
  * Kept same APPLICATION_TYPE as Optimizer 2
2. Alternated relu and sigmoid activation for each layer
3. Changed optimizer to adam

In [27]:
application_df_3 = pd.read_csv("/content/drive/MyDrive/CoLabs/deep-learning-challenge/Resources/charity_data.csv")
application_df_3.drop(columns=['EIN', 'NAME', 'STATUS', 'CLASSIFICATION', 'SPECIAL_CONSIDERATIONS', 'ASK_AMT'], inplace=True)
application_df_3.head()

,APPLICATION_TYPE,AFFILIATION,USE_CASE,ORGANIZATION,INCOME_AMT,IS_SUCCESSFUL
0,T10,Independent,ProductDev,Association,0,1
1,T3,Independent,Preservation,Co-operative,1-9999,1
2,T5,CompanySponsored,ProductDev,Association,0,0
3,T3,CompanySponsored,Preservation,Trust,10000-24999,1
4,T3,Independent,Heathcare,Trust,100000-499999,1

In [28]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#cutoff value = 1000
application_types_to_replace = []
for value in application_df_3['APPLICATION_TYPE']: 
  if value in application_types_to_replace:
    continue
  elif application_df_3['APPLICATION_TYPE'].value_counts()[value] < 1000:
    application_types_to_replace.append(value)

#print(f"Application types to replace: {application_types_to_replace}")

# Replace in dataframe
for app in application_types_to_replace:
    application_df_3['APPLICATION_TYPE'] = application_df_3['APPLICATION_TYPE'].replace(app,"Other")

In [29]:
# Convert categorical data to numeric with `pd.get_dummies`
# non-numeric columns: APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, INCOME_AMT, SPECIAL_CONSIDERATIONS, ASK_AMT
#create a dataframe with dummy data
optimize_3_df = pd.get_dummies(data=application_df_3, columns=['APPLICATION_TYPE', 'AFFILIATION','USE_CASE', 'ORGANIZATION', 'INCOME_AMT'])
optimize_3_df

,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,1,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,0,0,1,0,0,0,1,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,0,0,1,0,0,0,0,0,1,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,0,0,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
34295,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
34296,0,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
34297,1,0,0,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
34298,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0

In [30]:
# Split our preprocessed data into our features and target arrays
y = optimize_3_df['IS_SUCCESSFUL'].values
X = optimize_3_df.drop(['IS_SUCCESSFUL'],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

<ipython-input-30-c6ac7f277a8e>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = optimize_3_df.drop(['IS_SUCCESSFUL'],1).values

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  42
hidden_nodes_layer2 = 21
hidden_nodes_layer3 = 10
nn_3 = tf.keras.models.Sequential()

# First hidden layer
nn_3.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
# Second hidden layer
nn_3.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

#Third hidden layer
nn_3.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn_3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 42)                1302

 dense_9 (Dense)             (None, 21)                903

 dense_10 (Dense)            (None, 10)                220

 dense_11 (Dense)            (None, 1)                 11

=================================================================
Total params: 2,436
Trainable params: 2,436
Non-trainable params: 0
_________________________________________________________________

In [32]:
# Compile the model
nn_3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
my_callbacks = keras.callbacks.ModelCheckpoint(filepath='/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/saved_model_weights_optimizer3.h5', save_weights_only=True, save_freq=5)

# Train the model
fit_model = nn_3.fit(X_train_scaled, y_train, epochs=100, callbacks=[my_callbacks])

Epoch 1/100
804/804 [==============================] - 9s 9ms/step - loss: 0.5936 - accuracy: 0.7127
Epoch 2/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5737 - accuracy: 0.7246
Epoch 3/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5724 - accuracy: 0.7264
Epoch 4/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5713 - accuracy: 0.7253
Epoch 5/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5709 - accuracy: 0.7263
Epoch 6/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5703 - accuracy: 0.7268
Epoch 7/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5705 - accuracy: 0.7254
Epoch 8/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5699 - accuracy: 0.7260
Epoch 9/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5698 - accuracy: 0.7264
Epoch 10/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5693 - accuracy: 0.7273
Epoch 11/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5693 - accuracy: 0.7266
Epoch 12/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5692 - accuracy: 0.7266
Epoch 13/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5692 - accuracy: 0.7276
Epoch 14/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5685 - accuracy: 0.7270
Epoch 15/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5684 - accuracy: 0.7276
Epoch 16/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5686 - accuracy: 0.7271
Epoch 17/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5680 - accuracy: 0.7280
Epoch 18/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5679 - accuracy: 0.7276
Epoch 19/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5677 - accuracy: 0.7275
Epoch 20/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5682 - accuracy: 0.7281
Epoch 21/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5678 - accuracy: 0.7274
Epoch 22/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5677 - accuracy: 0.7278
Epoch 23/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5677 - accuracy: 0.7278
Epoch 24/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5674 - accuracy: 0.7270
Epoch 25/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5669 - accuracy: 0.7282
Epoch 26/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5671 - accuracy: 0.7280
Epoch 27/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5672 - accuracy: 0.7290
Epoch 28/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5672 - accuracy: 0.7276
Epoch 29/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5668 - accuracy: 0.7267
Epoch 30/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5668 - accuracy: 0.7285
Epoch 31/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5669 - accuracy: 0.7281
Epoch 32/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5667 - accuracy: 0.7287
Epoch 33/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5667 - accuracy: 0.7282
Epoch 34/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5665 - accuracy: 0.7285
Epoch 35/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5666 - accuracy: 0.7287
Epoch 36/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5664 - accuracy: 0.7287
Epoch 37/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5664 - accuracy: 0.7281
Epoch 38/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5665 - accuracy: 0.7284
Epoch 39/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5662 - accuracy: 0.7286
Epoch 40/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5663 - accuracy: 0.7292
Epoch 41/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5659 - accuracy: 0.7292
Epoch 42/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5662 - accuracy: 0.7288
Epoch 43/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5661 - accuracy: 0.7285
Epoch 44/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5661 - accuracy: 0.7282
Epoch 45/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5658 - accuracy: 0.7288
Epoch 46/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5658 - accuracy: 0.7289
Epoch 47/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5659 - accuracy: 0.7285
Epoch 48/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5659 - accuracy: 0.7289
Epoch 49/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5655 - accuracy: 0.7287
Epoch 50/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5655 - accuracy: 0.7294
Epoch 51/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5656 - accuracy: 0.7280
Epoch 52/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5654 - accuracy: 0.7287
Epoch 53/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5658 - accuracy: 0.7285
Epoch 54/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5653 - accuracy: 0.7292
Epoch 55/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5653 - accuracy: 0.7301
Epoch 56/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5656 - accuracy: 0.7292
Epoch 57/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5654 - accuracy: 0.7297
Epoch 58/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5653 - accuracy: 0.7294
Epoch 59/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5648 - accuracy: 0.7294
Epoch 60/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5652 - accuracy: 0.7292
Epoch 61/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5652 - accuracy: 0.7295
Epoch 62/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5654 - accuracy: 0.7290
Epoch 63/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5651 - accuracy: 0.7294
Epoch 64/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5648 - accuracy: 0.7292
Epoch 65/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5650 - accuracy: 0.7293
Epoch 66/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5649 - accuracy: 0.7289
Epoch 67/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5649 - accuracy: 0.7296
Epoch 68/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5647 - accuracy: 0.7288
Epoch 69/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5649 - accuracy: 0.7291
Epoch 70/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5648 - accuracy: 0.7293
Epoch 71/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5646 - accuracy: 0.7296
Epoch 72/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5648 - accuracy: 0.7289
Epoch 73/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5647 - accuracy: 0.7293
Epoch 74/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5645 - accuracy: 0.7297
Epoch 75/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5646 - accuracy: 0.7287
Epoch 76/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5644 - accuracy: 0.7296
Epoch 77/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5646 - accuracy: 0.7286
Epoch 78/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5646 - accuracy: 0.7296
Epoch 79/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5644 - accuracy: 0.7296
Epoch 80/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5647 - accuracy: 0.7298
Epoch 81/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5645 - accuracy: 0.7294
Epoch 82/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5645 - accuracy: 0.7288
Epoch 83/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5642 - accuracy: 0.7288
Epoch 84/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5643 - accuracy: 0.7296
Epoch 85/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5644 - accuracy: 0.7294
Epoch 86/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5643 - accuracy: 0.7293
Epoch 87/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5644 - accuracy: 0.7294
Epoch 88/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5642 - accuracy: 0.7290
Epoch 89/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5644 - accuracy: 0.7294
Epoch 90/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5642 - accuracy: 0.7294
Epoch 91/100
804/804 [==============================] - 6s 7ms/step - loss: 0.5643 - accuracy: 0.7300
Epoch 92/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5641 - accuracy: 0.7297
Epoch 93/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5642 - accuracy: 0.7298
Epoch 94/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5641 - accuracy: 0.7296
Epoch 95/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5640 - accuracy: 0.7294
Epoch 96/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5639 - accuracy: 0.7292
Epoch 97/100
804/804 [==============================] - 7s 8ms/step - loss: 0.5640 - accuracy: 0.7294
Epoch 98/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5641 - accuracy: 0.7290
Epoch 99/100
804/804 [==============================] - 12s 16ms/step - loss: 0.5641 - accuracy: 0.7292
Epoch 100/100
804/804 [==============================] - 7s 9ms/step - loss: 0.5642 - accuracy: 0.7286

In [34]:
# Evaluate the model using the test data
model_loss_3, model_accuracy_3 = nn_3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"\nOptimizer 3 \n Loss: {model_loss_3}, Accuracy: {model_accuracy_3}")

268/268 - 1s - loss: 0.5719 - accuracy: 0.7259 - 539ms/epoch - 2ms/step

Optimizer 3
 Loss: 0.571895182132721, Accuracy: 0.7259474992752075

In [35]:
# Export our model to HDF5 file
nn_3.save('/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/AlphabetSoupCharity_Optimized_3.h5')

# Optimization 4
Model optimizations: 
1. Changed data preprocessing: 
  * Kept same preprocessing as Optimization 2 (more APPLICATION_TYPEs and CLASSIFICATIONs for a total of 70 featuers)
2. Used relu in hidden layers and sigmoid for output layer
3. Added two hidden layers
4. Increased the number of neurons in the first hidden layer to 2x the input layer
5. Used sigmoid as the activation function for all layers
6. Kept optimizer of adam

In [37]:
#  Import and read the charity_data.csv.
import pandas as pd 
application_df_4 = pd.read_csv("/content/drive/MyDrive/CoLabs/deep-learning-challenge/Resources/charity_data.csv")
application_df_4.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [38]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df_4.drop(columns=['EIN', 'NAME', 'STATUS'], inplace=True)
application_df_4

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,N,36500179,0

In [39]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#cutoff value = 10
application_types_to_replace = []
for value in application_df_4['APPLICATION_TYPE']: 
  if value in application_types_to_replace:
    continue
  elif application_df_4['APPLICATION_TYPE'].value_counts()[value] < 10:
    application_types_to_replace.append(value)

# Replace in dataframe
for app in application_types_to_replace:
    application_df_4['APPLICATION_TYPE'] = application_df_4['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df_4['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: APPLICATION_TYPE, dtype: int64

In [40]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#cutoff value = 10
classifications_to_replace = []
for value in application_df_4['CLASSIFICATION']: 
  if value in classifications_to_replace:
    continue
  elif application_df_4['CLASSIFICATION'].value_counts()[value] < 10:
    classifications_to_replace.append(value)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df_4['CLASSIFICATION'] = application_df_4['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df_4['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: CLASSIFICATION, dtype: int64

In [41]:
# Convert categorical data to numeric with `pd.get_dummies`

# non-numeric columns: APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, INCOME_AMT, SPECIAL_CONSIDERATIONS
#create a dataframe with dummy data
dummies_df_4 = pd.get_dummies(data=application_df_4, columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])
dummies_df_4

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,5000,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,108590,1,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
2,5000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,6692,1,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,142590,1,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,5000,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34295,5000,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34296,5000,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34297,5000,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,36500179,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0

In [42]:
# Split our preprocessed data into our features and target arrays
y = dummies_df_4['IS_SUCCESSFUL'].values
X = dummies_df_4.drop(['IS_SUCCESSFUL'],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

<ipython-input-42-e4698f06cc03>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dummies_df_4.drop(['IS_SUCCESSFUL'],1).values

In [43]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [45]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  140
hidden_nodes_layer2 = 70
hidden_nodes_layer3 = 35
hidden_nodes_layer4 = 18
hidden_nodes_layer5 = 9

nn_4 = tf.keras.models.Sequential()

# First hidden layer
nn_4.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="sigmoid")
)
# Second hidden layer
nn_4.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn_4.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Fourth hidden layer
nn_4.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="sigmoid"))

# Fifth hidden layer
nn_4.add(tf.keras.layers.Dense(units=hidden_nodes_layer5, activation="sigmoid"))

# Output layer
nn_4.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_4.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_17 (Dense)            (None, 140)               9940

 dense_18 (Dense)            (None, 70)                9870

 dense_19 (Dense)            (None, 35)                2485

 dense_20 (Dense)            (None, 18)                648

 dense_21 (Dense)            (None, 9)                 171

 dense_22 (Dense)            (None, 1)                 10

=================================================================
Total params: 23,124
Trainable params: 23,124
Non-trainable params: 0
_________________________________________________________________

In [46]:
# Compile the model
nn_4.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [47]:
my_callbacks = keras.callbacks.ModelCheckpoint(filepath='/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/saved_model_weights_4.h5', save_weights_only=True, save_freq=5)

# Train the model
fit_model = nn_4.fit(X_train_scaled, y_train, epochs=100, callbacks=[my_callbacks])

Epoch 1/100
804/804 [==============================] - 10s 11ms/step - loss: 0.6051 - accuracy: 0.6991
Epoch 2/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5749 - accuracy: 0.7308
Epoch 3/100
804/804 [==============================] - 11s 14ms/step - loss: 0.5727 - accuracy: 0.7318
Epoch 4/100
804/804 [==============================] - 12s 15ms/step - loss: 0.5719 - accuracy: 0.7316
Epoch 5/100
804/804 [==============================] - 11s 13ms/step - loss: 0.5709 - accuracy: 0.7316
Epoch 6/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5693 - accuracy: 0.7322
Epoch 7/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5687 - accuracy: 0.7311
Epoch 8/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5614 - accuracy: 0.7321
Epoch 9/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5535 - accuracy: 0.7310
Epoch 10/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5518 - accuracy: 0.7317
Epoch 11/100
804/804 [==============================] - 8s 9ms/step - loss: 0.5502 - accuracy: 0.7325
Epoch 12/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5491 - accuracy: 0.7318
Epoch 13/100
804/804 [==============================] - 8s 9ms/step - loss: 0.5484 - accuracy: 0.7317
Epoch 14/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5474 - accuracy: 0.7329
Epoch 15/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5462 - accuracy: 0.7333
Epoch 16/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5460 - accuracy: 0.7317
Epoch 17/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5457 - accuracy: 0.7325
Epoch 18/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5448 - accuracy: 0.7346
Epoch 19/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5441 - accuracy: 0.7329
Epoch 20/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5437 - accuracy: 0.7321
Epoch 21/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5432 - accuracy: 0.7329
Epoch 22/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5423 - accuracy: 0.7347
Epoch 23/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5423 - accuracy: 0.7332
Epoch 24/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5419 - accuracy: 0.7325
Epoch 25/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5411 - accuracy: 0.7339
Epoch 26/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5409 - accuracy: 0.7350
Epoch 27/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5405 - accuracy: 0.7353
Epoch 28/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5403 - accuracy: 0.7336
Epoch 29/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5400 - accuracy: 0.7363
Epoch 30/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5388 - accuracy: 0.7349
Epoch 31/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5398 - accuracy: 0.7348
Epoch 32/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5388 - accuracy: 0.7357
Epoch 33/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5389 - accuracy: 0.7363
Epoch 34/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5388 - accuracy: 0.7348
Epoch 35/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5380 - accuracy: 0.7359
Epoch 36/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5378 - accuracy: 0.7344
Epoch 37/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5377 - accuracy: 0.7352
Epoch 38/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5371 - accuracy: 0.7356
Epoch 39/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5370 - accuracy: 0.7357
Epoch 40/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5368 - accuracy: 0.7357
Epoch 41/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5366 - accuracy: 0.7347
Epoch 42/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5366 - accuracy: 0.7356
Epoch 43/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5360 - accuracy: 0.7358
Epoch 44/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5360 - accuracy: 0.7360
Epoch 45/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5360 - accuracy: 0.7367
Epoch 46/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5356 - accuracy: 0.7379
Epoch 47/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5355 - accuracy: 0.7356
Epoch 48/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5353 - accuracy: 0.7377
Epoch 49/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5350 - accuracy: 0.7380
Epoch 50/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5348 - accuracy: 0.7378
Epoch 51/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5343 - accuracy: 0.7377
Epoch 52/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5338 - accuracy: 0.7395
Epoch 53/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5339 - accuracy: 0.7392
Epoch 54/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5338 - accuracy: 0.7395
Epoch 55/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5334 - accuracy: 0.7390
Epoch 56/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5332 - accuracy: 0.7396
Epoch 57/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5331 - accuracy: 0.7397
Epoch 58/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5331 - accuracy: 0.7403
Epoch 59/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5326 - accuracy: 0.7404
Epoch 60/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5323 - accuracy: 0.7390
Epoch 61/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5323 - accuracy: 0.7399
Epoch 62/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5317 - accuracy: 0.7414
Epoch 63/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5317 - accuracy: 0.7390
Epoch 64/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5314 - accuracy: 0.7406
Epoch 65/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5312 - accuracy: 0.7405
Epoch 66/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5311 - accuracy: 0.7389
Epoch 67/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5309 - accuracy: 0.7411
Epoch 68/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5306 - accuracy: 0.7397
Epoch 69/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5308 - accuracy: 0.7398
Epoch 70/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5301 - accuracy: 0.7411
Epoch 71/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5300 - accuracy: 0.7408
Epoch 72/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5298 - accuracy: 0.7412
Epoch 73/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5296 - accuracy: 0.7413
Epoch 74/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5296 - accuracy: 0.7414
Epoch 75/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5293 - accuracy: 0.7407
Epoch 76/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5294 - accuracy: 0.7414
Epoch 77/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5293 - accuracy: 0.7422
Epoch 78/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5293 - accuracy: 0.7421
Epoch 79/100
804/804 [==============================] - 8s 11ms/step - loss: 0.5289 - accuracy: 0.7417
Epoch 80/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5287 - accuracy: 0.7426
Epoch 81/100
804/804 [==============================] - 8s 11ms/step - loss: 0.5285 - accuracy: 0.7420
Epoch 82/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5288 - accuracy: 0.7423
Epoch 83/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5286 - accuracy: 0.7427
Epoch 84/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5284 - accuracy: 0.7414
Epoch 85/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5285 - accuracy: 0.7421
Epoch 86/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5279 - accuracy: 0.7431
Epoch 87/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5278 - accuracy: 0.7427
Epoch 88/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5278 - accuracy: 0.7422
Epoch 89/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5277 - accuracy: 0.7428
Epoch 90/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5275 - accuracy: 0.7428
Epoch 91/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5277 - accuracy: 0.7429
Epoch 92/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5273 - accuracy: 0.7424
Epoch 93/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5270 - accuracy: 0.7428
Epoch 94/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5272 - accuracy: 0.7431
Epoch 95/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5272 - accuracy: 0.7413
Epoch 96/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5269 - accuracy: 0.7421
Epoch 97/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5268 - accuracy: 0.7437
Epoch 98/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5268 - accuracy: 0.7428
Epoch 99/100
804/804 [==============================] - 8s 10ms/step - loss: 0.5270 - accuracy: 0.7427
Epoch 100/100
804/804 [==============================] - 9s 11ms/step - loss: 0.5265 - accuracy: 0.7426

In [49]:
# Evaluate the model using the test data
model_loss_4, model_accuracy_4 = nn_4.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss_4}, Accuracy: {model_accuracy_4}")

268/268 - 2s - loss: 0.5631 - accuracy: 0.7278 - 2s/epoch - 6ms/step
Loss: 0.5630967617034912, Accuracy: 0.7278134226799011

In [50]:
# Export our model to HDF5 file
nn_4.save('/content/drive/MyDrive/CoLabs/deep-learning-challenge/Deep Learning Challenge/Output/AlphabetSoupCharity_Optimized_4.h5')

# Optimization Results

In [51]:
print(f"\nOptimizer 1: Loss: {model_loss_1}, Accuracy: {model_accuracy_1}")
print(f"\nOptimizer 2: Loss: {model_loss_2}, Accuracy: {model_accuracy_2}")
print(f"\nOptimizer 3: Loss: {model_loss_3}, Accuracy: {model_accuracy_3}")
print(f"\nOptimizer 4: Loss: {model_loss_4}, Accuracy: {model_accuracy_4}")

Optimizer 1: Loss: 0.5614355802536011, Accuracy: 0.7325947284698486

Optimizer 2: Loss: 0.563554584980011, Accuracy: 0.728396475315094

Optimizer 3: Loss: 0.571895182132721, Accuracy: 0.7259474992752075

Optimizer 4: Loss: 0.5630967617034912, Accuracy: 0.7278134226799011